site_name: WLAN Pi Documentation Project
nav:
    - Home: index.md
    - What's New For V2?: v2/index.md
    - FAQ: faq.md
    - Getting Started: get_started/index.md
    - Supported Hardware: supported_hardware.md 
    - Toolset: toolset/toolset.md
    - Administration: admin/index.md
    - News: news.md
    - Support: support.md
    - Getting Involved: get_involved/index.md
    - Suppliers: suppliers.md
    - About: about.md
    - V1 Docs (Deprecated):
        - Home: v1/index.md
        - About: v1/about.md
        - Getting Started:
            - Overview: v1/getting_started_overview.md
            - Buy a Kit: v1/getting_started_buy_kit.md
            - Build Your Own: v1/getting_started_build_your_own.md
        - Packages: 
            - Overview: v1/packages.md
            - Perf Measurement:
                - HTML Speedtest: v1/pkg_perf_speedtest.md
                - iPerf: v1/pkg_perf_iperf.md
                - Ruckus Zap: v1/pkg_perf_zap.md
            - Analysis:
                - Kismet: v1/pkg_analysis_kismet.md
                - Horst: v1/pkg_analysis_horst.md
                - Scapy: v1/pkg_analysis_scapy.md
                - Termshark: v1/pkg_analysis_termshark.md
                - extcap: v1/pkg_analysis_extcap.md
            - Utilities:
                - Wi-Fi Console: v1/pkg_util_wconsole.md
                - Hotspot Mode: v1/pkg_util_hotspot.md
                - Wiperf: v1/pkg_util_wiperf.md
                - Profiler: v1/pkg_util_profiler.md
        - Videos: v1/videos.md
        - FAQ: v1/faq.md
        - Useful Links: v1/useful_links.md
theme:
    name: 'material'
    custom_dir: overrides
    icon:
        logo: material/wifi
    language: en
extra_css:
  - extra.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.tabbed
plugins:
    - search
    - git-revision-date-localized
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/wlan-pi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wlanpi